AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'Guardfile'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
