LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
  - 'lib/tasks/**/*'
  - 'db/schema.rb'
  - 'db/migrate/**/*'
  - 'Guardfile'
Metrics/MethodLength:
  Exclude:
  - 'spec/**/*'
  - 'db/migrate/**/*'
Style/Documentation:
  Enabled: false
