steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.production.enc
  - --plaintext-file=.env.production
  - --location=global
  - --keyring=builder-keyring
  - --key=builder-key
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/bluegiant-ui:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/bluegiant-ui:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/bluegiant-ui:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bluegiant-ui:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud components install kubectl
    gcloud container clusters get-credentials bluegiant-cluster --zone asia-northeast-a
    kubectl set image deployment/bluegiant-ui bluegiant-ui=gcr.io/$PROJECT_ID/blugiant-ui:$COMMIT_SHA
images: ['gcr.io/$PROJECT_ID/bluegiant-ui']
