steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.production.enc
  - --plaintext-file=.env.production
  - --location=global
  - --keyring=builder-keyring
  - --key=builder-key
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/bluegiant-ui:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/bluegiant-ui:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/bluegiant-ui:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bluegiant-ui:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud components install kubectl
    gcloud container clusters get-credentials bluegiant-cluster --zone asia-northeast1-a
    kubectl set image deployment/bluegiant-ui bluegiant-ui=gcr.io/$PROJECT_ID/bluegiant-ui:$COMMIT_SHA
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    curl -X POST -H 'Content-type: application/json' \
      --data '{"attachments":[{"color":"#36a64f","text":"Successfully deployed lastest master commit","fields":[{"title":"Container Image","value":"High","short":false}]}]}' \
      https://hooks.slack.com/services/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
images: ['gcr.io/$PROJECT_ID/bluegiant-ui']
