apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
  creationTimestamp: 2017-10-23T13:18:05Z
  generation: 10
  labels:
    run: bluegiant-ui
  name: bluegiant-ui
  namespace: default
  resourceVersion: "206810"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/bluegiant-ui
  uid: 9b04e46d-b7f4-11e7-9d5f-42010a9200c0
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bluegiant-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: bluegiant-ui
    spec:
      containers:
      - image: gcr.io/bluegiant-183723/bluegiant-ui:latest
        imagePullPolicy: IfNotPresent
        name: bluegiant-ui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: BLUEGIANT_DATABASE_HOST
          value: 127.0.0.1
        - name: BLUEGIANT_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: BLUEGIANT_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
      - image: gcr.io/cloudsql-docker/gce-proxy:1.11
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
        - /cloud_sql_proxy
        - --dir=/cloudsql
        - -instances=bluegiant-183723:asia-northeast1:bluegiant=tcp:3306
        - -credential_file=/secrets/cloudsql/credentials.json
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/ssl/certs
        - name: cloudsql
          mountPath: /cloudsql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
      - hostPath:
          path: /etc/ssl/certs
        name: ssl-certs
      - emptyDir: {}
        name: cloudsql
status:
  collisionCount: 1
  conditions:
  - lastTransitionTime: 2017-10-23T13:18:05Z
    lastUpdateTime: 2017-10-23T13:18:05Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
