version: '2'
services:
  app:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/home/app
      - bundle:/bundle
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    links:
      - mysql
  mysql:
    image: mysql:5.7.18
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3307:3307"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
